# Generated by Django 3.2.13 on 2022-06-19 11:57

import api_basic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0002_article_hotel_main_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='hotel_Main_Img',
        ),
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=api_basic.models.upload_to),
        ),
    ]
