# Generated by Django 3.2.13 on 2022-06-19 22:18

import api_basic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0003_auto_20220619_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image_url',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='article',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to=api_basic.models.upload_to),
        ),
    ]
