# Generated by Django 3.2.13 on 2022-06-20 07:20

import api_basic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0005_auto_20220620_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='artwork',
            field=models.ImageField(blank=True, null=True, upload_to=api_basic.models.upload_to),
        ),
    ]
