# Generated by Django 3.2.13 on 2022-06-20 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0007_remove_article_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='artwork',
        ),
    ]
